# Simple workflow for deploying static content to GitHub Pages
name: Publish to npm

on:
  release:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: bun i
      - name: Build
        run: bun run build:lib
      - name: Update version in package.json
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Updating package.json version to $VERSION"
          npm version --no-git-tag-version $VERSION  
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
