name: Sync upstream branch

on:
  schedule:
    - cron: '14 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "sync"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: upstream

      - name: Git
        run: |
          set -x
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add up https://github.com/scratchfoundation/scratch-gui.git
          git pull up develop
          git push -u origin upstream
          git push
