name: Sync upstream branch

on:
  schedule:
    - cron: '14 6 * * *'
  workflow_dispatch:
    inputs:
      cmd:
        type: string
        description: 'Custom commands'
        required: false
        default: ''

permissions:
  contents: write

concurrency:
  group: "sync"
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # uses: actions/checkout@v4
        # with:
        #   ref: upstream
        run: |
          git clone --depth=1 -b upstream \
            'https://github-actions[bot]:${{ github.token }}@github.com/${{ github.repository }}' \
            .

      - name: Custom commands
        if: ${{ inputs.cmd != '' }}
        run: ${{ inputs.cmd }}

      - name: Git
        run: |
          set -x
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add up https://github.com/scratchfoundation/scratch-gui.git
          # git switch -c upstream
          git pull up develop
          git push -u origin upstream
          git push
